name: Run tests

on:
  pull_request:

jobs:
  run-step:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Check Dockerfile for valid manifest SHAs
        if: "contains(github.event.pull_request.changed_files, 'Dockerfile')"
        uses: kbottla/gh_actions/.github/workflows/_check_docker_sha_is_manifest.yaml@master
        with:
          file-path: Dockerfile