name: Run tests

on:
  pull_request:

jobs:
  check_docker_file:
    uses: kbottla/gh_actions/.github/workflows/_check_docker_sha_is_manifest.yaml@main
    with:
      file-path: Dockerfile
    if: "contains(github.event.pull_request.changed_files, 'Dockerfile')"
    name: Check Dockerfile for valid manifest SHAs
